### ISSUE TITLE
.sol file for this project

### ISSUE THREAD

**Issue by Tatoo988** [0xKaizendev/Web3-Kickstarter#1]
Hi! Is there a way you can add the .sol file you used for this project, I'm thinking about fork it since I have some other functions that I'm thinking I should add or tweak to the contract but I'd be very helpful to have the deployed .sol to only rewrite some of them.

Thanks in advance.

**Comment by 0xKaizendev** [comment]
Hey @Tatoo988 just did it, check the contract folder
